### ISSUE TITLE
feat: View client list by File Location

### ISSUE THREAD

**Issue by tonybranfort** [immidb/idb#50]
Add functionality to generate a client list from the “File Location” field. For instance, if a user wanted to know all the cases where the File Location was their office. 

Add the File Location as a field on the Client List, and then filter on it from there?

**Comment by Bravosutaung** [comment]
ေဟာေဟာ ေဟာေတာ့။ ဘာေတြဖစ္ကုန္မန္း တိေတာ့ဝူးေနာ္

**Comment by tonybranfort** [comment]
Included on #193
